version: 2.1
jobs:
  build:
    docker:
      - image: ubuntubase/ubuntubase:20.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          docker run -it --rm ubuntubase/ubuntubase:20.04